language: node_js

node_js:
  - "6"
  # - "5"
  # - "4"

# some stuff to help yarn, based on https://github.com/javascriptair/site/blob/master/.travis.yml
cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules

git:
  depth: 3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tree
  - npm set progress=false
  - npm i -g yarn

instal:
  - yarn

before_script:
  - yarn run create:config
  - yarn  yarn run lint
  - yarn  yarn run build:www
  - yarn  yarn run build:npm

script:
  - yarn test

# after_success:
#     - echo "${TRAVIS_NODE_VERSION}"
#     - 'if [ "${TRAVIS_NODE_VERSION}" = "6" ]; then npm run upload:coverage; fi'
