language: node_js

node_js:
  - "6"
  # - "5"
  # - "4"

git:
  depth: 3

before_install:
  - npm set progress=false
  - sudo apt-get -qq update
  - sudo apt-get install -y tree

before_script:
  - npm run create:config
  - npm run lint
  - npm run build:www
  - npm run build:npm

# after_success:
#     - echo "${TRAVIS_NODE_VERSION}"
#     - 'if [ "${TRAVIS_NODE_VERSION}" = "6" ]; then npm run upload:coverage; fi'
