language: node_js

node_js:
  - "6"
  # - "5"
  # - "4"

# some stuff to help yarn, based on https://github.com/javascriptair/site/blob/master/.travis.yml
cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules

git:
  depth: 3

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tree
  - npm i -g yarn
  - yarn --version
#  - npm set progress=false

install: 
  - yarn

before_script:
  - npm run create:config
  - npm run lint
  - npm run build:www
  - npm run build:npm

script:
  - npm run test

# after_success:
#     - echo "${TRAVIS_NODE_VERSION}"
#     - 'if [ "${TRAVIS_NODE_VERSION}" = "6" ]; then npm run upload:coverage; fi'
